module.exports = Object.freeze({
  TABLE_EVENTS: "events",
  TABLE_SCOPE: "scopes",
  TABLE_USERS: "users",
  TABLE_POSTS: "posts",
  TABLE_POLLS: "polls",
  TABLE_CHANNELS : "channels",
  TABLE_COLLEGES : "colleges",
  TABLE_ACTIVITY: "activities",
  TABLE_USERS_ADMIN: "users_admin",
  TABLE_USER_ACTIVITY: "user_activities",
  TABLE_USER_ANALYTICS : "user_analytics",
  TABLE_ADMIN_ANALYTICS : "user_admin_analytics",
  MAX_RETRIES_MESSAGING: 5,
});